In [1]:
import numpy as np
import math

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product between Q and Kᵀ
    scores = np.dot(Q, K.T)

    # Step 2: Scale by √d (dimension of K)
    d = K.shape[1]
    scaled_scores = scores / math.sqrt(d)

    # Step 3: Apply softmax to get attention weights
    exp_scores = np.exp(scaled_scores - np.max(scaled_scores, axis=1, keepdims=True))  # for numerical stability
    attention_weights = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Step 4: Multiply weights by V
    output = np.dot(attention_weights, V)

    print("Attention Weights:\n", attention_weights)
    print("Output:\n", output)

# Test input
Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

scaled_dot_product_attention(Q, K, V)


Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]
Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
